// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit.
// Source: shared/icons.svg (269 icons). Run `npm run gen:icons` to refresh.

export type IconName =
  | 'add'
  | 'add-small'
  | 'adrenaline'
  | 'ai'
  | 'alert'
  | 'approve'
  | 'assign'
  | 'assigned'
  | 'audio'
  | 'audio-headset'
  | 'audio-mute'
  | 'auto-brightness'
  | 'battery'
  | 'battery-0'
  | 'battery-10'
  | 'battery-100'
  | 'battery-20'
  | 'battery-30'
  | 'battery-40'
  | 'battery-50'
  | 'battery-60'
  | 'battery-70'
  | 'battery-80'
  | 'battery-90'
  | 'battery-disconnected'
  | 'bidirectional'
  | 'black-stretch'
  | 'blink'
  | 'bluetooth'
  | 'bolt'
  | 'boom-mic'
  | 'bounce'
  | 'breathing'
  | 'breeze'
  | 'brightness'
  | 'brightness-high'
  | 'brightness-low'
  | 'browser'
  | 'buttons'
  | 'calculator'
  | 'calibration'
  | 'camera-photo'
  | 'camera-video'
  | 'cardioid'
  | 'charging-0'
  | 'charging-10'
  | 'charging-100'
  | 'charging-20'
  | 'charging-30'
  | 'charging-40'
  | 'charging-50'
  | 'charging-60'
  | 'charging-70'
  | 'charging-80'
  | 'charging-90'
  | 'charging-checking'
  | 'charging-regular'
  | 'charging-wired'
  | 'charging-wireless'
  | 'chat-support'
  | 'check'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevron-up-down'
  | 'clone'
  | 'close'
  | 'collapse'
  | 'color-palette'
  | 'confetti'
  | 'contrast'
  | 'crayon'
  | 'cycle'
  | 'dance'
  | 'decline'
  | 'denied'
  | 'details'
  | 'devices'
  | 'direction-ccw'
  | 'direction-cw'
  | 'direction-down'
  | 'direction-inward'
  | 'direction-left'
  | 'direction-outward'
  | 'direction-right'
  | 'direction-up'
  | 'download'
  | 'dpi-combine'
  | 'dpi-split'
  | 'duplicate'
  | 'edit'
  | 'emoji'
  | 'eq'
  | 'expand'
  | 'explosion'
  | 'export'
  | 'eyedropper'
  | 'fade'
  | 'feedback'
  | 'filter'
  | 'fireworks'
  | 'flame'
  | 'folder'
  | 'frost'
  | 'game-chat'
  | 'game-mode'
  | 'gaming'
  | 'grid'
  | 'heart'
  | 'heartbeat'
  | 'heatmap'
  | 'hide'
  | 'home'
  | 'hourglass'
  | 'image'
  | 'image-add'
  | 'image-edit'
  | 'image-upload'
  | 'implosion'
  | 'import'
  | 'info'
  | 'invaders'
  | 'keys'
  | 'library'
  | 'lift'
  | 'light'
  | 'lightning'
  | 'lights'
  | 'link-off'
  | 'link-on'
  | 'link-window'
  | 'location-bl'
  | 'location-br'
  | 'location-tl'
  | 'location-tr'
  | 'lock-off'
  | 'lock-on'
  | 'macro'
  | 'maelstrom'
  | 'mail'
  | 'matrix'
  | 'media-next'
  | 'media-play'
  | 'media-player'
  | 'media-previous'
  | 'media-record'
  | 'media-stop'
  | 'message'
  | 'meteor'
  | 'mic'
  | 'mic-mute'
  | 'microphone'
  | 'minus'
  | 'mirror'
  | 'monitor-pivot'
  | 'moon'
  | 'more'
  | 'none'
  | 'notification'
  | 'omnidirectional'
  | 'open-app'
  | 'paint'
  | 'paintbucket'
  | 'performance'
  | 'personalize'
  | 'placeholder'
  | 'placeholder-1'
  | 'placeholder-2'
  | 'platform-android'
  | 'platform-blizzard'
  | 'platform-discord'
  | 'platform-ea'
  | 'platform-eneba'
  | 'platform-epic'
  | 'platform-facebook'
  | 'platform-fanatical'
  | 'platform-gamers-gate'
  | 'platform-gamesplanet'
  | 'platform-gog'
  | 'platform-google'
  | 'platform-google-play-games'
  | 'platform-green-man-gaming'
  | 'platform-hp'
  | 'platform-humble-bundle'
  | 'platform-hyperx'
  | 'platform-indie-gala'
  | 'platform-netease'
  | 'platform-nvidia'
  | 'platform-omen'
  | 'platform-riot'
  | 'platform-rockstar'
  | 'platform-steam'
  | 'platform-twitch'
  | 'platform-ubisoft'
  | 'platform-utomik'
  | 'platform-wechat'
  | 'platform-wegame'
  | 'platform-wikipedia'
  | 'platform-wild-tangent'
  | 'platform-windows'
  | 'platform-x'
  | 'platform-xbox'
  | 'platform-youtube'
  | 'play'
  | 'play-fill'
  | 'play-pause'
  | 'princess'
  | 'profile'
  | 'puddle'
  | 'puzzle'
  | 'question'
  | 'rain'
  | 'rainbow'
  | 'refresh'
  | 'reset'
  | 'river'
  | 'royal'
  | 'saturation'
  | 'screen-mirror'
  | 'search'
  | 'select'
  | 'sensor'
  | 'settings'
  | 'share'
  | 'sharpness'
  | 'shop'
  | 'shortcut'
  | 'show'
  | 'shuffle'
  | 'sidetone'
  | 'silent'
  | 'singularity'
  | 'snake'
  | 'snow'
  | 'solid'
  | 'sparks'
  | 'spatial-audio'
  | 'spiral'
  | 'star'
  | 'star-fill'
  | 'stereo'
  | 'stream'
  | 'sun'
  | 'sunise'
  | 'sunset'
  | 'swipe'
  | 'target'
  | 'tesla'
  | 'tetris'
  | 'thermometer'
  | 'trash'
  | 'twilight'
  | 'twinkle'
  | 'type-mode'
  | 'undo'
  | 'upload'
  | 'vaporware'
  | 'video-capture'
  | 'volume-down'
  | 'volume-up'
  | 'vu-meter'
  | 'waka'
  | 'wave'
  | 'windows-folder'
  | 'work'
  | 'zephyr'
  | 'zoom-in'
  | 'zoom-out';

export const ICON_NAMES: IconName[] = [
  'add',
  'add-small',
  'adrenaline',
  'ai',
  'alert',
  'approve',
  'assign',
  'assigned',
  'audio',
  'audio-headset',
  'audio-mute',
  'auto-brightness',
  'battery',
  'battery-0',
  'battery-10',
  'battery-100',
  'battery-20',
  'battery-30',
  'battery-40',
  'battery-50',
  'battery-60',
  'battery-70',
  'battery-80',
  'battery-90',
  'battery-disconnected',
  'bidirectional',
  'black-stretch',
  'blink',
  'bluetooth',
  'bolt',
  'boom-mic',
  'bounce',
  'breathing',
  'breeze',
  'brightness',
  'brightness-high',
  'brightness-low',
  'browser',
  'buttons',
  'calculator',
  'calibration',
  'camera-photo',
  'camera-video',
  'cardioid',
  'charging-0',
  'charging-10',
  'charging-100',
  'charging-20',
  'charging-30',
  'charging-40',
  'charging-50',
  'charging-60',
  'charging-70',
  'charging-80',
  'charging-90',
  'charging-checking',
  'charging-regular',
  'charging-wired',
  'charging-wireless',
  'chat-support',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-up-down',
  'clone',
  'close',
  'collapse',
  'color-palette',
  'confetti',
  'contrast',
  'crayon',
  'cycle',
  'dance',
  'decline',
  'denied',
  'details',
  'devices',
  'direction-ccw',
  'direction-cw',
  'direction-down',
  'direction-inward',
  'direction-left',
  'direction-outward',
  'direction-right',
  'direction-up',
  'download',
  'dpi-combine',
  'dpi-split',
  'duplicate',
  'edit',
  'emoji',
  'eq',
  'expand',
  'explosion',
  'export',
  'eyedropper',
  'fade',
  'feedback',
  'filter',
  'fireworks',
  'flame',
  'folder',
  'frost',
  'game-chat',
  'game-mode',
  'gaming',
  'grid',
  'heart',
  'heartbeat',
  'heatmap',
  'hide',
  'home',
  'hourglass',
  'image',
  'image-add',
  'image-edit',
  'image-upload',
  'implosion',
  'import',
  'info',
  'invaders',
  'keys',
  'library',
  'lift',
  'light',
  'lightning',
  'lights',
  'link-off',
  'link-on',
  'link-window',
  'location-bl',
  'location-br',
  'location-tl',
  'location-tr',
  'lock-off',
  'lock-on',
  'macro',
  'maelstrom',
  'mail',
  'matrix',
  'media-next',
  'media-play',
  'media-player',
  'media-previous',
  'media-record',
  'media-stop',
  'message',
  'meteor',
  'mic',
  'mic-mute',
  'microphone',
  'minus',
  'mirror',
  'monitor-pivot',
  'moon',
  'more',
  'none',
  'notification',
  'omnidirectional',
  'open-app',
  'paint',
  'paintbucket',
  'performance',
  'personalize',
  'placeholder',
  'placeholder-1',
  'placeholder-2',
  'platform-android',
  'platform-blizzard',
  'platform-discord',
  'platform-ea',
  'platform-eneba',
  'platform-epic',
  'platform-facebook',
  'platform-fanatical',
  'platform-gamers-gate',
  'platform-gamesplanet',
  'platform-gog',
  'platform-google',
  'platform-google-play-games',
  'platform-green-man-gaming',
  'platform-hp',
  'platform-humble-bundle',
  'platform-hyperx',
  'platform-indie-gala',
  'platform-netease',
  'platform-nvidia',
  'platform-omen',
  'platform-riot',
  'platform-rockstar',
  'platform-steam',
  'platform-twitch',
  'platform-ubisoft',
  'platform-utomik',
  'platform-wechat',
  'platform-wegame',
  'platform-wikipedia',
  'platform-wild-tangent',
  'platform-windows',
  'platform-x',
  'platform-xbox',
  'platform-youtube',
  'play',
  'play-fill',
  'play-pause',
  'princess',
  'profile',
  'puddle',
  'puzzle',
  'question',
  'rain',
  'rainbow',
  'refresh',
  'reset',
  'river',
  'royal',
  'saturation',
  'screen-mirror',
  'search',
  'select',
  'sensor',
  'settings',
  'share',
  'sharpness',
  'shop',
  'shortcut',
  'show',
  'shuffle',
  'sidetone',
  'silent',
  'singularity',
  'snake',
  'snow',
  'solid',
  'sparks',
  'spatial-audio',
  'spiral',
  'star',
  'star-fill',
  'stereo',
  'stream',
  'sun',
  'sunise',
  'sunset',
  'swipe',
  'target',
  'tesla',
  'tetris',
  'thermometer',
  'trash',
  'twilight',
  'twinkle',
  'type-mode',
  'undo',
  'upload',
  'vaporware',
  'video-capture',
  'volume-down',
  'volume-up',
  'vu-meter',
  'waka',
  'wave',
  'windows-folder',
  'work',
  'zephyr',
  'zoom-in',
  'zoom-out',
];
